In [1]:
import torch 



In [2]:
x=torch.Tensor([5,3])
y=torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


### Tensor is just nothing but arrays 

In [3]:
x=torch.zeros([2,5])

In [4]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y=torch.rand([2,5])

In [7]:
y

tensor([[0.1239, 0.4956, 0.7842, 0.8066, 0.1381],
        [0.7327, 0.3497, 0.7390, 0.2748, 0.8105]])

In [8]:
y.view([1,10])

tensor([[0.1239, 0.4956, 0.7842, 0.8066, 0.1381, 0.7327, 0.3497, 0.7390, 0.2748,
         0.8105]])

### View is just reshape in pytorch

In [9]:
y

tensor([[0.1239, 0.4956, 0.7842, 0.8066, 0.1381],
        [0.7327, 0.3497, 0.7390, 0.2748, 0.8105]])